version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  repo_discovery:
    build:
      context: .
      dockerfile: Dockerfile.repo_discovery
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - rabbitmq

  commit_monitor:
    build:
      context: .
      dockerfile: Dockerfile.commit_monitor
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - rabbitmq

  commit_manager:
    build:
      context: .
      dockerfile: Dockerfile.commit_manager
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - rabbitmq
